
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4285:4285"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_OPENAI_API_KEY=your_openai_api_key
